---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana-operator
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Operator configuration
    namespaceScope: false
    # watchNamespaces not set = operator watches all namespaces

    # Resource limits for the operator pod
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi

    # Enable leader election for HA deployments
    leaderElect: true

    # Health probes
    healthProbe:
      enabled: true
